### ISSUE TITLE
Allow passing a token as a command line argument

### ISSUE THREAD

**Issue by JoelSanchez** [ritiek/scribd-downloader#31]
I am using the 30-day trial and I wanted to download a document. scribdl was only able to access to the preview but I was able to put my token in the code, and scribdl downloaded the whole document.

Can the token be a command line argument, to make this easier?

**Comment by ritiek** [comment]
> I wanted to download a document

I think you're referring to a book rather than a document here.

 > scribdl was only able to access to the preview

Yup, this script at the moment does not do anything to fake itself as a premium account. So, it can only download the preview version of a book.

> but I was able to put my token in the code, and scribdl downloaded the whole document.

When using a premium account, scribd generates a special token which can access premium content as well. So, replacing it in the code is one way to fetch premium content. But as I mentioned in #28, the token remains valid for only a few minutes, so a single token won't able to fetch large content which could take more than a few minutes to fetch all the content.

The current best way I've found is to replicate the browser cookies of a premium account in our code and then we could pass it along with POST request when requesting for token.
I've been doing some testing; I replicated these cookies in code a week ago and these same cookies are still providing me those special tokens which can gain access to premium-content.

We may able to hard-code these cookies in our code to access premium-content but I am not sure if there are any risks involved.

**Comment by JoelSanchez** [comment]
Sorry, not sure if it's a book or a document:
https://es.scribd.com/read/312838327/Curso-aprendiz-de-Bruja

I also noticed that the tokens are quite short-lived. In this case, the command line argument could be a file with cookies, similar to curl's `-b`.

**Comment by ritiek** [comment]
I've included premium headers and cookies in the code itself now. So you can now download complete books out of the box (#32).

In case you want to use your own; replace the values of [`headers` and `cookies` lines](https://github.com/ritiek/scribd-downloader/blob/9ab728f7cabd2d2a3708d758d4f7c209b7722a29/scribdl/book.py#L150-L156) in the code with your values (`data` can take any value but it is mandatory to pass it to fetch a premium token).
